### PR TITLE
fix: ensure documents portal on activate

### LINKED ISSUE #48: bwrap: Can't find source path /run/user/1000/doc/by-app/${app_id}: No such file or directory
VS Code version: 1.64.0 (host, official vscode yum repo)
Flatpak vscode extension version: 0.0.16

It basically only happens every bootup. A weird workaround is to close vscode and open any other flatpak app in host. Then reopen vscode, now everything works properly. The workaround lasts, until another boot. I think something may not be initialized during the configuration of the extension.

Steps to reproduce:
1. Boot device
2. Open vscode
3. Open build terminal or trigger rust analyzer

Output:
`bwrap: Can't find source path /run/user/1000/doc/by-app/${app_id}: No such file or directory`

### PR DESCRIPTION
**Pull request by SeaDve**
Fixes #48

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -1,10 +1,23 @@
...
 import * as yaml from 'js-yaml'
 import { FlatpakManifestSchema } from './flatpak.types'
 import { FlatpakManifest } from './terminal'
 
+export const ensureDocumentsPortal = async (): Promise<void> => {
+  try {
+    const bus = dbus.sessionBus();
+    const obj = await bus.getProxyObject('org.freedesktop.portal.Documents', '/org/freedesktop/portal/documents');
+    const portal = obj.getInterface('org.freedesktop.portal.Documents');
+    await portal.GetMountPoint()
```
Comment (bilelmoussaoui) [inline src/utils.ts:14]:
```suggestion
    await portal.GetMountPoint();
```

**Comment by bilelmoussaoui** [comment]
Otherwise looks good to me!

File: src/utils.ts (hunk 1 above)
Comment (SeaDve) [reply src/utils.ts:14]: I realized no other lines have a semicolon. should I remove the semicolon on the first three lines instead?
